In [1]:
import pandas as pd
import numpy as np
import math
ratings_df=pd.read_csv(R"A:\Hari\ml-latest-small\ml-latest-small\ratings.csv")
movies_df=pd.read_csv(R"A:\Hari\ml-latest-small\ml-latest-small\movies.csv")
tags=pd.read_csv(R"A:\Hari\ml-latest-small\ml-latest-small\tags.csv")

In [3]:
ratings_df

userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [4]:
movies_df

movieId                                              title  \
0           1                                   Toy Story (1995)   
1           2                                     Jumanji (1995)   
2           3                            Grumpier Old Men (1995)   
3           4                           Waiting to Exhale (1995)   
4           5                 Father of the Bride Part II (1995)   
5           6                                        Heat (1995)   
6           7                                     Sabrina (1995)   
7           8                                Tom and Huck (1995)   
8           9                                Sudden Death (1995)   
9          10                                   GoldenEye (1995)   
10         11                     American President, The (1995)   
11         12                 Dracula: Dead and Loving It (1995)   
12         13                                       Balto (1995)   
13         14                                       Nixon (1995)   
14         15                            Cutthroat Island (1995)   
15         16                                      Casino (1995)   
16         17                       Sense and Sensibility (1995)   
17         18                                  Four Rooms (1995)   
18         19              Ace Ventura: When Nature Calls (1995)   
19         20                                 Money Train (1995)   
20         21                                  Get Shorty (1995)   
21         22                                     Copycat (1995)   
22         23                                   Assassins (1995)   
23         24                                      Powder (1995)   
24         25                           Leaving Las Vegas (1995)   
25         26                                     Othello (1995)   
26         27                                Now and Then (1995)   
27         28                                  Persuasion (1995)   
28         29  City of Lost Children, The (Cité des enfants p...   
29         30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...       ...                                                ...   
9095   159690  Teenage Mutant Ninja Turtles: Out of the Shado...   
9096   159755          Popstar: Never Stop Never Stopping (2016)   
9097   159858                             The Conjuring 2 (2016)   
9098   159972                     Approaching the Unknown (2016)   
9099   160080                                Ghostbusters (2016)   
9100   160271                        Central Intelligence (2016)   
9101   160438                                Jason Bourne (2016)   
9102   160440                             The Maid's Room (2014)   
9103   160563                        The Legend of Tarzan (2016)   
9104   160565                    The Purge: Election Year (2016)   
9105   160567              Mike & Dave Need Wedding Dates (2016)   
9106   160590                         Survive and Advance (2013)   
9107   160656                                    Tallulah (2016)   
9108   160718                                       Piper (2016)   
9109   160954                                       Nerve (2016)   
9110   161084                       My Friend Rockefeller (2015)   
9111   161155                                   Sunspring (2016)   
9112   161336                  Author: The JT LeRoy Story (2016)   
9113   161582                          Hell or High Water (2016)   
9114   161594               Kingsglaive: Final Fantasy XV (2016)   
9115   161830                                        Body (2015)   
9116   161918                Sharknado 4: The 4th Awakens (2016)   
9117   161944              The Last Brickmaker in America (2001)   
9118   162376                                    Stranger Things   
9119   162542                                      Rustom (2016)   
9120   162672                                Mohenjo Daro (2016)   
9121   163056                               Shin Godzilla (201

In [18]:
ratings_df.rename(columns={'movieId':'MovieID','userID':'UserID','rating':'Rating'},inplace=True)
movies_df.rename(columns={'movieId':'MovieID'},inplace=True)

In [19]:
ratings_df

UserID  MovieID  Rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [20]:
R_df = ratings_df.pivot(index = 'UserID', columns ='MovieID', values = 'Rating').fillna(0)
R_df.head()

MovieID  1       2       3       4       5       6       7       8       \
UserID                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     4.0     0.0     0.0     0.0     0.0     0.0   

MovieID  9       10       ...    161084  161155  161594  161830  161918  \
UserID                    ...                                             
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     4.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     4.0   ...       0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

MovieID  161944  162376  162542  162672  163949  
UserID                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  

[5 rows x 9066 columns]

In [66]:
R_df.head(50)

MovieID  1       2       3       4       5       6       7       8       \
UserID                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     4.0     0.0     0.0     0.0     0.0     0.0   
6           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7           3.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
11          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
12          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13          5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
14          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
15          2.0     2.0     0.0     0.0     4.5     4.0     0.0     0.0   
16          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
17          0.0     0.0     0.0     0.0     0.0     4.5     0.0     0.0   
18          0.0     0.0     0.0     0.0     3.0     4.0     3.0     0.0   
19          3.0     3.0     3.0     3.0     0.0     3.0     3.0     0.0   
20          3.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
21          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
22          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
23          3.0     0.0     0.0     0.0     0.0     3.5     0.0     0.0   
24          0.0     0.0     0.0     0.0     0.0     5.0     0.0     0.0   
25          0.0     0.0     3.0     0.0     0.0     0.0     0.0     0.0   
26          5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
27          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
28          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
29          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
30          4.0     2.0     0.0     0.0     0.0     4.0     0.0     4.0   
31          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
32          0.0     4.0     0.0     0.0     0.0     0.0     0.0     0.0   
33          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
34          0.0     0.0     0.0     0.0     0.0     3.0     0.0     0.0   
35          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
36          0.0     0.0     0.0     0.0     0.0     3.0     0.0     0.0   
37          4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
38          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
39          0.0     0.0     0.0     0.0     0.0     4.0     0.0     0.0   
40          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
41          0.0     3.5     0.0     0.0     0.0     0.0     0.0     0.0   
42          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
43          4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
44          4.0     0.0     5.0     0.0     3.0     3.0     0.0     0.0   
45          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
46          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
47          5.0     5.0     0.0     0.0     0.0     0.0     0.0     0.0   
48          4.0     3.5     0.0     0.0     0.0     0.0     0.0     0.0   
49          0.0     5.0     0.0     0.0     0.0     0.0     0.0     0.0   
50          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

MovieID  9       10       ...    161084  161155  161594  161830  161918  \
UserID                  

In [26]:
ratings_df.UserID.nunique()

671

In [25]:
len(R_df.as_matrix())

C:\Users\clustrex-1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


671

In [30]:
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [46]:
np.mean(R, axis = 1)

array([0.00562541, 0.02923009, 0.02007501, 0.09783808, 0.04312817,
       0.01582837, 0.03364218, 0.04947055, 0.01864108, 0.01875138,
       0.01709685, 0.01853077, 0.02189499, 0.00650783, 0.49161703,
       0.01318112, 0.14990073, 0.01819987, 0.16490183, 0.03557247,
       0.06265167, 0.07947276, 0.29092213, 0.00849327, 0.00893448,
       0.06579528, 0.0097066 , 0.02360468, 0.00694904, 0.41986543,
       0.03171189, 0.01941319, 0.04985661, 0.08118244, 0.00529451,
       0.04147364, 0.01433929, 0.05255901, 0.02592102, 0.02139863,
       0.08487756, 0.03099493, 0.03639974, 0.00926539, 0.00838297,
       0.02128833, 0.01621443, 0.19887492, 0.03783366, 0.01665564,
       0.01356717, 0.02768586, 0.01411869, 0.01842047, 0.01522171,
       0.2081403 , 0.09121994, 0.02746525, 0.02652769, 0.02536951,
       0.05994926, 0.02360468, 0.04020516, 0.00926539, 0.01235385,
       0.02139863, 0.04268696, 0.04919479, 0.03695125, 0.03849548,
       0.01080962, 0.06833223, 0.59921685, 0.02217075, 0.05244

In [39]:
671/11

61.0

In [31]:
len(np.mean(R, axis = 1))

671

In [45]:
user_ratings_mean.reshape(-1, 1)

array([[0.00562541],
       [0.02923009],
       [0.02007501],
       [0.09783808],
       [0.04312817],
       [0.01582837],
       [0.03364218],
       [0.04947055],
       [0.01864108],
       [0.01875138],
       [0.01709685],
       [0.01853077],
       [0.02189499],
       [0.00650783],
       [0.49161703],
       [0.01318112],
       [0.14990073],
       [0.01819987],
       [0.16490183],
       [0.03557247],
       [0.06265167],
       [0.07947276],
       [0.29092213],
       [0.00849327],
       [0.00893448],
       [0.06579528],
       [0.0097066 ],
       [0.02360468],
       [0.00694904],
       [0.41986543],
       [0.03171189],
       [0.01941319],
       [0.04985661],
       [0.08118244],
       [0.00529451],
       [0.04147364],
       [0.01433929],
       [0.05255901],
       [0.02592102],
       [0.02139863],
       [0.08487756],
       [0.03099493],
       [0.03639974],
       [0.00926539],
       [0.00838297],
       [0.02128833],
       [0.01621443],
       [0.198

In [32]:
R - user_ratings_mean.reshape(-1, 1)

array([[-0.00562541, -0.00562541, -0.00562541, ..., -0.00562541,
        -0.00562541, -0.00562541],
       [-0.02923009, -0.02923009, -0.02923009, ..., -0.02923009,
        -0.02923009, -0.02923009],
       [-0.02007501, -0.02007501, -0.02007501, ..., -0.02007501,
        -0.02007501, -0.02007501],
       ...,
       [-0.01367748, -0.01367748, -0.01367748, ..., -0.01367748,
        -0.01367748, -0.01367748],
       [ 3.98698434, -0.01301566, -0.01301566, ..., -0.01301566,
        -0.01301566, -0.01301566],
       [ 4.95030885, -0.04969115, -0.04969115, ..., -0.04969115,
        -0.04969115, -0.04969115]])

In [28]:
R = R_df.as_matrix()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

C:\Users\clustrex-1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [47]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)

In [49]:
U

array([[-0.00016784, -0.00262409,  0.00115034, ..., -0.0016466 ,
         0.00385665,  0.00194852],
       [-0.01194155, -0.01895569, -0.00436913, ...,  0.06627468,
         0.01095882,  0.02037542],
       [-0.03304357,  0.00884139, -0.01776162, ...,  0.00794732,
        -0.01104013,  0.01723412],
       ...,
       [-0.01203739, -0.0089091 , -0.00239065, ..., -0.00129099,
         0.00210224,  0.00737041],
       [-0.00621775, -0.00019208, -0.00382755, ...,  0.0104679 ,
         0.00144254,  0.01492536],
       [ 0.03981078,  0.0400138 , -0.02134693, ..., -0.00959032,
        -0.01384089,  0.04609078]])

In [52]:
Vt

array([[-1.62597887e-02,  1.15529719e-02,  1.65617781e-02, ...,
        -7.35678860e-06,  1.88352072e-04,  1.44795715e-03],
       [ 1.69123825e-03, -1.09626697e-02, -2.74717954e-04, ...,
        -7.94725980e-04, -4.87199612e-04, -4.89578501e-04],
       [-2.36777797e-02,  2.24332643e-02,  2.00020650e-03, ...,
         4.53924961e-04,  5.52541550e-04,  1.03757309e-03],
       ...,
       [ 4.33543163e-02,  6.94114639e-02,  3.14867235e-02, ...,
         2.22426937e-03,  2.19165637e-03, -6.13023224e-03],
       [-2.71524602e-02, -1.18045196e-02,  6.33159662e-03, ...,
        -1.48176418e-03, -1.38168693e-03,  1.88028230e-03],
       [ 8.54208781e-02,  3.15694928e-02,  9.21294390e-03, ...,
        -5.08949609e-03, -5.11809108e-03, -3.93498880e-03]])

In [50]:
sigma

array([ 67.60554014,  67.9019903 ,  68.36901996,  68.87678354,
        69.36040309,  70.40559402,  70.67868738,  71.11142588,
        71.53634058,  71.82885532,  72.17402558,  72.49218005,
        73.17578618,  73.92529791,  74.39862887,  74.96695425,
        75.15748411,  76.3922596 ,  77.19546498,  77.88829516,
        78.74878972,  79.21912641,  79.88957685,  80.29941237,
        81.74224585,  82.07564572,  84.0252619 ,  84.33524515,
        85.46807357,  87.1592136 ,  88.50454414,  89.85457756,
        91.66600372,  92.03234586,  92.40518797,  97.27752595,
        99.23143011, 104.99431013, 105.72437051, 110.15522471,
       116.29714259, 118.66831462, 122.82232277, 135.96585855,
       138.92664501, 145.53348705, 160.48685586, 199.93327534,
       242.13488251, 462.13504865])

In [55]:
sigma = np.diag(sigma)
sigma

array([[ 67.60554014,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  67.9019903 ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  68.36901996, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 199.93327534,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
        242.13488251,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 462.13504865]])

In [58]:
np.dot(np.dot(U, sigma), Vt)

array([[-0.05986445,  0.03950502, -0.01046003, ..., -0.01199032,
        -0.01172307, -0.01044427],
       [ 0.39060495,  1.37721009, -0.21803758, ..., -0.02818329,
        -0.03069834, -0.03580718],
       [ 1.3255439 ,  0.24642986, -0.03203712, ..., -0.00946358,
        -0.01328286, -0.02643204],
       ...,
       [ 0.71501061, -0.14906121,  0.17613243, ..., -0.0121038 ,
        -0.01401811, -0.0206782 ],
       [ 1.56885432,  0.07156243, -0.05937879, ..., -0.00570558,
        -0.00631738, -0.00843177],
       [ 3.4582134 ,  0.27913198, -0.11711277, ..., -0.03691362,
        -0.03868926, -0.06652866]])

In [62]:
np.array([-0.05986445,  0.03950502, -0.01046003, -0.01199032,
        -0.01172307, -0.01044427]) + np.array([0.00562541])

array([-0.05423904,  0.04513043, -0.00483462, -0.00636491, -0.00609766,
       -0.00481886])

In [64]:
-0.05986445 + 0.00562541

-0.05423904

In [60]:
user_ratings_mean.reshape(-1, 1)

array([[0.00562541],
       [0.02923009],
       [0.02007501],
       [0.09783808],
       [0.04312817],
       [0.01582837],
       [0.03364218],
       [0.04947055],
       [0.01864108],
       [0.01875138],
       [0.01709685],
       [0.01853077],
       [0.02189499],
       [0.00650783],
       [0.49161703],
       [0.01318112],
       [0.14990073],
       [0.01819987],
       [0.16490183],
       [0.03557247],
       [0.06265167],
       [0.07947276],
       [0.29092213],
       [0.00849327],
       [0.00893448],
       [0.06579528],
       [0.0097066 ],
       [0.02360468],
       [0.00694904],
       [0.41986543],
       [0.03171189],
       [0.01941319],
       [0.04985661],
       [0.08118244],
       [0.00529451],
       [0.04147364],
       [0.01433929],
       [0.05255901],
       [0.02592102],
       [0.02139863],
       [0.08487756],
       [0.03099493],
       [0.03639974],
       [0.00926539],
       [0.00838297],
       [0.02128833],
       [0.01621443],
       [0.198

In [59]:
np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

array([[-5.42390333e-02,  4.51304289e-02, -4.83461757e-03, ...,
        -6.36490827e-03, -6.09765683e-03, -4.81885918e-03],
       [ 4.19835043e-01,  1.40644018e+00, -1.88807492e-01, ...,
         1.04679741e-03, -1.46825089e-03, -6.57708637e-03],
       [ 1.34561891e+00,  2.66504861e-01, -1.19621144e-02, ...,
         1.06114277e-02,  6.79214329e-03, -6.35703450e-03],
       ...,
       [ 7.28688090e-01, -1.35383733e-01,  1.89809902e-01, ...,
         1.57367435e-03, -3.40631718e-04, -7.00072377e-03],
       [ 1.58186999e+00,  8.45780940e-02, -4.63631293e-02, ...,
         7.31008459e-03,  6.69828780e-03,  4.58389107e-03],
       [ 3.50790455e+00,  3.28823135e-01, -6.74216131e-02, ...,
         1.27775344e-02,  1.10018934e-02, -1.68375103e-02]])

In [83]:
print(np.dot(U, sigma).shape)
print(Vt.shape)
print(U.shape)
print(sigma.shape)

(671, 50)
(50, 9066)
(671, 50)
(50, 50)


In [57]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = R_df.columns)

In [65]:
preds_df

MovieID    1         2         3         4         5         6         7       \
0       -0.054239  0.045130 -0.004835 -0.019817 -0.011284  0.041373 -0.007822   
1        0.419835  1.406440 -0.188807  0.156658  0.268032  0.414698  0.052172   
2        1.345619  0.266505 -0.011962  0.012278  0.079508  0.090960 -0.122094   
3        1.133455  1.046982  0.141275  0.081841 -0.339675 -1.484659 -0.263096   
4        1.389578  1.466495  0.605557 -0.029647  0.729380 -0.118539 -0.026017   
5        0.351379  0.147783 -0.226190  0.024425 -0.028854  0.052569 -0.095954   
6        2.710704  0.684846  0.702097  0.141979  0.025992  0.079456  0.386194   
7        1.286794 -0.263419 -0.147525  0.056464  0.612119  0.048448  0.055058   
8        1.803813 -0.024808 -0.113694 -0.026134  0.188041  0.660766  0.039552   
9        0.498709 -0.216453 -0.262796  0.001221 -0.233903 -0.085897 -0.181951   
10       0.298924  0.006766 -0.031805  0.016027 -0.117802  0.280893 -0.128224   
11       0.183047  0.179267  0.186287  0.055718  0.105107  0.145885  0.161255   
12       2.233535  0.622080 -0.025171  0.014307  0.069452 -0.231845 -0.091142   
13       0.593835  0.036823  0.005703 -0.001961 -0.095341 -0.028088 -0.074412   
14       1.006034  2.409513  0.278231  0.058565  4.731423  4.182127  0.036119   
15      -0.113357 -0.134332 -0.249100 -0.045181  0.078126 -0.015525 -0.196962   
16       0.777199  0.007064 -0.822508  0.201619  0.044513  3.002940  0.463650   
17       2.603456  0.200121  2.220603  0.135537  1.666834  2.891869  2.106293   
18       4.529441  1.744093  1.462131  0.791312  0.230640  2.966768  1.653985   
19       2.891267  0.752881  0.414691  0.007321  0.096795  0.555748  0.251070   
20       1.159589  1.002537  0.228784  0.214228 -0.337895  0.206057  0.341784   
21       1.745768  0.598647 -0.115416  0.031446  0.092062  0.700399 -0.123187   
22       1.924983 -0.374784  0.574936  0.038999  0.764722  3.554816  0.345166   
23       1.022327  0.471111  0.554630  0.003727  0.307408  1.001422  0.388033   
24       1.500813  0.127582  1.113809  0.059725  0.724995  1.237719  0.904904   
25       3.949766  0.312456  0.772692  0.005354  0.026360  1.458092  0.562729   
26       0.420125 -0.221079 -0.377600 -0.050156 -0.104421  0.147877 -0.363278   
27       0.035281 -0.098552 -0.251137  0.020741 -0.148588 -0.077531  0.096304   
28      -0.011672  0.075295 -0.008744 -0.013254  0.014679  0.096820  0.023476   
29       5.451525  1.949996 -0.410094  0.151153 -0.441204  4.226505 -0.109154   
..            ...       ...       ...       ...       ...       ...       ...   
641      0.154129  0.104004 -0.074560  0.027260 -0.082479  0.260482  0.115863   
642      0.523967 -0.306340  0.031179  0.008724 -0.005047  0.122928 -0.104771   
643      0.804237 -0.387216  0.052906  0.016796 -0.012035  0.527337 -0.116666   
644     -0.067597  0.327278 -0.124306  0.016709  0.017740 -0.135289 -0.078929   
645      5.525118  1.930533  1.422226  0.149802  0.255729 -0.447268  0.541682   
646      3.090243 -0.632093 -0.191784  0.134027 -0.579425  2.641218 -0.494571   
647      1.320263  0.749291  0.961706 -0.100278 -0.037106  1.307686 -0.157287   
648      1.519949  1.544385  0.166525  0.210215  0.292219  1.105433  0.194287   
649      1.194844  0.257919  1.084082  0.085298  0.829491  1.354814  1.070652   
650      0.614993 -0.194408  0.021819  0.033122  0.044624 -0.263839  0.055207   
651     -0.724501 -1.335021 -0.090932  0.044446  0.755402  0.573301 -0.500040   
652      2.328783  1.046489  0.218367  0.045670  0.013641  0.156447  0.045494   
653      4.884880  2.908804  1.256549 -0.028386  4.099977  0.348320  0.642122   
654      0.832515  0.979949 -0.010148  0.099953  0.032183  0.038046 -0.056829   
655      0.957937  0.102064 -0.214390 -0.035723 -0.514598 -0.105465 -0.367375   
656      0.494966  0.604792  0.072626  0.002426  0.144047  0.408010  0.007963   
657      1.683320  0.651494 -0.024633 -0.018680  0.238338  0.518744  0.016051   
658      3.153806  0.937370  1.

In [77]:
preds_df.iloc[60].sort_values(ascending=False)[1380]

1.8953585569744296

In [76]:
ratings_df.loc[(ratings_df['UserID'] == 60) ]

UserID  MovieID  Rating   timestamp
9142      60       16     4.5  1125828814
9143      60       21     3.0  1125829035
9144      60      111     4.5  1125829229
9145      60      163     4.0  1125828888
9146      60      173     3.5  1125828860
9147      60      235     5.0  1125829070
9148      60      466     4.0  1125828890
9149      60      541     5.0  1125829154
9150      60      608     4.0  1125829157
9151      60      653     2.5  1125828818
9152      60      720     4.0  1125829203
9153      60      745     3.5  1125829207
9154      60      858     5.0  1125829174
9155      60     1080     4.5  1125828831
9156      60     1090     4.0  1125828893
9157      60     1208     4.5  1125829194
9158      60     1209     4.0  1125829215
9159      60     1219     4.5  1125829161
9160      60     1221     5.0  1125829152
9161      60     1380     1.5  1125828900
9162      60     1485     2.5  1125828872
9163      60     1653     5.0  1125828865
9164      60     1673     4.5  1125829038
9165      60     1732     5.0  1125829088
9166      60     2012     4.0  1125828843
9167      60     2115     3.5  1125828850
9168      60     2174     4.0  1125828802
9169      60     2324     5.0  1125829168
9170      60     2640     4.0  1125828876
9171      60     2710     4.5  1125828811
9172      60     2797     4.0  1125828806
9173      60     3018     3.5  1125829108
9174      60     3160     3.5  1125829131
9175      60     3608     4.0  1125829115
9176      60     3726     3.0  1125829042
9177      60     3949     5.0  1125829144
9178      60     4973     4.5  1125829233
9179      60     5060     5.0  1125828895
9180      60     5618     4.0  1125829190
9181      60     5690     5.0  1125829218
9182      60     5945     4.0  1125829124
9183      60     5952     3.0  1125828855
9184      60     5959     4.5  1125829077
9185      60     5995     5.0  1125829169
9186      60     6350     5.0  1125829184
9187      60     6502     4.5  1125829017
9188      60     6957     3.0  1125829047
9189      60     7361     5.0  1125829192
9190      60     7387     4.5  1125829007
9191      60     8638     5.0  1125829249
9192      60     8981     5.0  1125829091
9193      60    27773     4.5  1125829180
9194      60    27801     3.0  1125828995
9195      60    27803     5.0  1125829225
9196      60    30749     5.0  1125829142

In [79]:
def recommend_movies(predictions_df, userID, movies_df, original_ratings_df, num_recommendations=5):
    
    # Get and sort the user's predictions
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df.UserID == (userID)]
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'MovieID', right_on = 'MovieID').
                     sort_values(['Rating'], ascending=False)
                 )

    print ('User {0} has already rated {1} movies.'.format(userID, user_full.shape[0]))
    print ('Recommending the highest {0} predicted ratings movies not already rated.'.format(num_recommendations))
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[~movies_df['MovieID'].isin(user_full['MovieID'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'MovieID',
               right_on = 'MovieID').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

already_rated, predictions = recommend_movies(preds_df, 10, movies_df, ratings_df, 10)

User 10 has already rated 46 movies.
Recommending the highest 10 predicted ratings movies not already rated.


In [80]:
already_rated

UserID  MovieID  Rating  timestamp  \
0       10       50     5.0  942766420   
19      10     1358     5.0  942766420   
42      10     2926     5.0  942767121   
35      10     2826     5.0  942766109   
34      10     2571     5.0  942766515   
30      10     2344     5.0  942766991   
28      10     1923     5.0  942766515   
26      10     1719     5.0  942766472   
23      10     1611     5.0  942767029   
45      10     3019     4.0  942767571   
20      10     1423     4.0  942766420   
40      10     2890     4.0  942765978   
38      10     2841     4.0  942766029   
4       10      345     4.0  942766603   
33      10     2539     4.0  942766845   
31      10     2406     4.0  942767328   
6       10      735     4.0  942766974   
10      10     1127     4.0  942767328   
2       10      318     4.0  942766515   
1       10      152     4.0  942766793   
25      10     1704     4.0  942766472   
15      10     1210     4.0  942767258   
14      10     1200     4.0  942767258   
11      10     1196     4.0  942767258   
18      10     1291     4.0  942767258   
12      10     1197     4.0  942767258   
17      10     1240     4.0  942767258   
13      10     1198     4.0  942767258   
39      10     2881     3.0  942766164   
37      10     2840     3.0  942766213   
36      10     2827     3.0  942766251   
3       10      344     3.0  942766603   
21      10     1459     3.0  942766725   
44      10     3005     3.0  942766059   
22      10     1499     3.0  942766845   
5       10      592     3.0  942767328   
29      10     2108     3.0  942766472   
16      10     1220     3.0  942767328   
7       10     1036     3.0  942767258   
24      10     1690     3.0  942766679   
8       10     1089     3.0  942766420   
43      10     2995     2.0  942766251   
9       10     1101     2.0  942767328   
41      10     2907     2.0  942766213   
32      10     2410     2.0  942767328   
27      10     1887     2.0  942766845   

                                                title  \
0                          Usual Suspects, The (1995)   
19                                 Sling Blade (1996)   
42                                   Hairspray (1988)   
35                           13th Warrior, The (1999)   
34                                 Matrix, The (1999)   
30                               Runaway Train (1985)   
28                There's Something About Mary (1998)   
26                        Sweet Hereafter, The (1997)   
23                        My Own Private Idaho (1991)   
45                            Drugstore Cowboy (1989)   
20                            Hearts and Minds (1996)   
40                                 Three Kings (1999)   
38                              Stir of Echoes (1999)   
4   Adventures of Priscilla, Queen of the Desert, ...   
33                                Analyze This (1999)   
31                         Romancing the Stone (1984)   
6          Cemetery Man (Dellamorte Dellamore) (1994)   
10                                  Abyss, The (1989)   
2                    Shawshank Redemption, The (1994)   
1                               Addiction, The (1995)   
25                           Good Will Hunting (1997)   
15  Star Wars: Episode VI - Return of the Jedi (1983)   
14                                      Aliens (1986)   
11  Star Wars: Episode V - The Empire Strikes Back...   
18          Indiana Jones and the Last Crusade (1989)   
12                         Princess Bride, The (1987)   
17                             Terminator, The (1984)   
13  Raiders of the Lost Ark (Indiana Jones and the...   
39                             Double Jeopardy (1999)   
37                                    Stigmata (1999)   
36                       Astronaut's Wife, The (1999)   
3                   Ace Ventura: Pet Detective (1994)   
21                              Absolute Power (1997)   
44                         Bone Collector, The (1999)   
22                                

In [81]:
predictions

MovieID                                              title  \
230       260          Star Wars: Episode IV - A New Hope (1977)   
264       296                                Pulp Fiction (1994)   
1561     2028                         Saving Private Ryan (1998)   
3825     4993  Lord of the Rings: The Fellowship of the Ring,...   
1006     1270                          Back to the Future (1985)   
517       589                  Terminator 2: Judgment Day (1991)   
4349     5952      Lord of the Rings: The Two Towers, The (2002)   
99        110                                  Braveheart (1995)   
4980     7153  Lord of the Rings: The Return of the King, The...   
995      1259                                 Stand by Me (1986)   

                              genres  
230          Action|Adventure|Sci-Fi  
264      Comedy|Crime|Drama|Thriller  
1561                Action|Drama|War  
3825               Adventure|Fantasy  
1006         Adventure|Comedy|Sci-Fi  
517                    Action|Sci-Fi  
4349               Adventure|Fantasy  
99                  Action|Drama|War  
4980  Action|Adventure|Drama|Fantasy  
995                  Adventure|Drama