In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a.dtype

dtype('int32')

In [8]:
b = np.array([1.2, 3, 5,5,5465])

In [9]:
b.dtype

dtype('float64')

In [10]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [28]:
np.arange(0.1,1,0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
np.linspace( 0, 2, 100 )

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [31]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.array((1,2,3)) + np.array((4,5,6))

array([5, 7, 9])

In [36]:
np.array((1,2,3)) / np.array((4,5,6))

array([0.25, 0.4 , 0.5 ])

In [37]:
np.array((1,2,3)) * np.array((4,5,6))

array([ 4, 10, 18])

In [38]:
np.array((1,2,3)) ** np.array((4,5,6))

array([  1,  32, 729], dtype=int32)

In [40]:
 a = np.array( [20,30,40,50,60,70,80,90] )
a

array([20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
a > 50

array([False, False, False, False,  True,  True,  True,  True])

In [45]:
A = np.array( [[1,1], [0,1]] )
A

array([[1, 1],
       [0, 1]])

In [44]:
B = np.array( [[2,0],[3,4]])
B

array([[2, 0],
       [3, 4]])

In [47]:
A @ B

array([[5, 4],
       [3, 4]])

In [49]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [51]:
a = np.random.random((2,3))
a

array([[0.50130622, 0.15427878, 0.91891939],
       [0.15742931, 0.98218456, 0.9545652 ]])

In [82]:
a = np.random.randint(2,1000,(3,4))
a

array([[963, 848, 344, 930],
       [388,  67, 653, 817],
       [467, 688, 980, 540]])

In [83]:
a.argmax()

10

In [89]:
a.argmin()

5

In [84]:
a.sum(axis = 0)

array([1818, 1603, 1977, 2287])

In [85]:
a.sum(axis = 1)

array([3085, 1925, 2675])

In [86]:
a.sum()

7685

In [87]:
a.min()

67

In [88]:
a.max()

980

In [58]:
a.mean()

468.0

In [90]:
a = np.random.randint(2,1000,(15,6))
a

array([[ 33, 624, 735, 638, 438, 848],
       [ 62, 214, 273, 976, 120, 385],
       [131, 588, 928, 620, 540, 382],
       [377, 688, 320, 599, 183, 715],
       [521, 818, 544, 736,  41, 125],
       [934, 688, 376, 950, 339, 137],
       [ 50, 226, 837, 944,  62, 701],
       [219, 284, 311, 450, 263, 845],
       [929, 162, 887, 188, 144, 584],
       [457,  92, 301, 380, 565, 146],
       [226, 250, 421, 251, 252, 260],
       [ 91, 143, 441, 798, 348, 298],
       [664, 952, 522, 125,  78, 278],
       [799, 175, 486, 620, 130, 386],
       [628, 316, 491, 925, 509, 439]])

In [91]:
a[a>600]

array([624, 735, 638, 848, 976, 928, 620, 688, 715, 818, 736, 934, 688,
       950, 837, 944, 701, 845, 929, 887, 798, 664, 952, 799, 620, 628,
       925])

In [92]:
a[:2]

array([[ 33, 624, 735, 638, 438, 848],
       [ 62, 214, 273, 976, 120, 385]])

In [66]:
a[4]

array([711, 965, 755, 746,  96, 389])

In [93]:
a[[1,4,6,7]]

array([[ 62, 214, 273, 976, 120, 385],
       [521, 818, 544, 736,  41, 125],
       [ 50, 226, 837, 944,  62, 701],
       [219, 284, 311, 450, 263, 845]])

In [94]:
a[[1,4,6,7]].T

array([[ 62, 521,  50, 219],
       [214, 818, 226, 284],
       [273, 544, 837, 311],
       [976, 736, 944, 450],
       [120,  41,  62, 263],
       [385, 125, 701, 845]])

In [67]:
a[3:7]

array([[713, 420,  56,  18, 941, 484],
       [711, 965, 755, 746,  96, 389],
       [153, 270, 433, 639, 137, 108],
       [944, 968, 528, 167, 573, 949]])

In [68]:
a[3:7,0:2]

array([[713, 420],
       [711, 965],
       [153, 270],
       [944, 968]])

In [69]:
a[3,0]

713

In [70]:
np.ceil(5.1)

6.0

In [75]:
np.ceil(5.0000003)

6.0

In [96]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
"""+3x+1y=+9
   +1x+2y=+8"""

In [77]:
A= np.array([[3,1],[1,2]])
b = np.array([9,8])

In [78]:
 np.linalg.solve(A,b)

array([2., 3.])